services:
  nextjs:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "2235:3000"
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.name=Portfolio
      - flame.url=https://portfolio.ethancls.com

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}