services:
  nextjs:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "2235:3000"
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}